### ISSUE TITLE
Add constructor unit tests for SP1ICS07Tendermint

### ISSUE THREAD

**Issue by gjermundgaraba** [cosmos/sp1-ics07-tendermint#129]
We should add some unit tests to make sure we only allow a correct setup of SP1ICS07Tendermint.

Ref: https://github.com/cosmos/sp1-ics07-tendermint/pull/128#discussion_r1828924729

**Comment by srdtrk** [comment]
issue moved https://github.com/cosmos/solidity-ibc-eureka/issues/129
