### ISSUE TITLE
Introduce caching for sp1 proofs of update client and membership program

### ISSUE THREAD

**Issue by srdtrk** [cosmos/sp1-ics07-tendermint#84]
## Description

Looking at the benchmarks published in [solidity-ibc-eureka](https://github.com/cosmos/solidity-ibc-eureka?tab=readme-ov-file#end-to-end-benchmarks), greater than 50% of the total gas costs for common functions such as `recvPacket`, `ackPacket`, and `timeoutPacket` is due to this client's `uc_and_membership` program and proof verification.

One of the common use cases for this repo is to have client updates be published regularly (e.g. every hour) by an aggragator, so that the users only pay gas for claiming their tokens, not for proof verification. (Users would still reserve the right to self generate proofs if they want). We currently don't support this use-case as all proof verification require an sp1 proof verification. I will propose two ways of implementing this:

### ~~Proposal 1: Use a solidity implementation of verify (non-)membership~~

Pure solidity implementations of verify (non-)membership exists (see #80), and they can be used to implement this feature. We would have the aggregator only post `update_client`, and then users would claim their funds by submitting a pure solidity membership proof (~56k gas, benchmark based on datachain). Thus, we would reduce the needed gas from ~320k -> ~56k.

### Proposal 2: Cache the SP1 proof

This would involve implementing a new contract which implements the `ISP1Verifier` interface. This new contract would store the hash of `(vKey, proof, publicValue)` pairs it verifies. (This caching can also be done within `SP1ICS07Tendermint.sol`) Then this proof would be submitted on chain by the aggregator, and users can re-submit this proof as needed.

**Comment by srdtrk** [comment]
We'll go with proposal 1

**Comment by crodriguezvega** [comment]
I will close this issue, since basically proposal 1 is covered in https://github.com/cosmos/sp1-ics07-tendermint/issues/80.

**Comment by srdtrk** [comment]
After a thorough discussion with @gjermundgaraba, we've concluded that pursuing a modified version of Proposal 2 is the better approach for the following reasons:

- **Lower gas consumption:** Proposal 2 is more efficient in terms of gas usage.
- **Simpler implementation:** It requires significantly fewer code additions compared to Proposal 1.
- **Greater flexibility:** While Proposal 1 is optimal for scenarios where users are primarily claiming their own funds, Proposal 2 offers the added benefit of supporting more robust aggregation strategies.

Given these advantages, I will be reopening this issue to proceed with the updated plan.
